"""initial_schema

Revision ID: 644191d9d074
Revises: 
Create Date: 2026-02-10 06:31:42.986190
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '644191d9d074'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
